// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: HelloWorld.proto

#include "HelloWorld.pb.h"
#include "HelloWorld.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace GrpcLibrary {

static const char* GrpcService_method_names[] = {
  "/GrpcLibrary.GrpcService/SayHello",
};

std::unique_ptr< GrpcService::Stub> GrpcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GrpcService::Stub> stub(new GrpcService::Stub(channel, options));
  return stub;
}

GrpcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(GrpcService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GrpcService::Stub::SayHello(::grpc::ClientContext* context, const ::GrpcLibrary::HelloRequest& request, ::GrpcLibrary::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::HelloRequest, ::GrpcLibrary::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void GrpcService::Stub::async::SayHello(::grpc::ClientContext* context, const ::GrpcLibrary::HelloRequest* request, ::GrpcLibrary::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::HelloRequest, ::GrpcLibrary::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::SayHello(::grpc::ClientContext* context, const ::GrpcLibrary::HelloRequest* request, ::GrpcLibrary::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::HelloReply>* GrpcService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::GrpcLibrary::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::HelloReply, ::GrpcLibrary::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::HelloReply>* GrpcService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::GrpcLibrary::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

GrpcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::HelloRequest, ::GrpcLibrary::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::HelloRequest* req,
             ::GrpcLibrary::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
}

GrpcService::Service::~Service() {
}

::grpc::Status GrpcService::Service::SayHello(::grpc::ServerContext* context, const ::GrpcLibrary::HelloRequest* request, ::GrpcLibrary::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace GrpcLibrary

